
services:
  app:
    build: .
    ports: ["8000:8000"]
    env_file: .env
    depends_on: 
      - db

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: password_manager
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: